### ISSUE TITLE
Error building image

### ISSUE THREAD

**Issue by joprice** [andyscott/rules_graal#14]
I'm getting the following error after upgrading to the latest version (https://github.com/andyscott/rules_graal/commit/1b5f6deef8352c4b64541bb0f699fd2af5ae6b0b):

```
Error: -H:CCompilerPath=external/local_config_cc/cc_wrapper.sh does not specify a path to an executable.
```

**Comment by marcguilera** [comment]
@joprice did you figure it out?

**Comment by virusdave** [comment]
Any update on this one?  Looks like it was fixed in a fork - should that be backported?
